Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::2048 }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-shanghai
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: 2048 demo
    Image: 'resources/icons/service_logo.png'
    Name: 2048
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: 2048
    Description: 2048
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/2048.tgz'
